data/implementations.yaml

Implementation is live at http://todobackend-spring.herokuapp.com/

Java 1.7 + Spring MVC

---

deployment-tooling/deploy-preview.sh
deployment-tooling/github-commit-status-helpers.sh

If I got this right then this PR itself should get some status updates as it's deployed to preview.todobackend.com

first pass at some bash scripting to report deploy status to Github

---

data/implementations.yaml

Finally, managed to finish this implementation. May not be the most elegant one...

Add Haskell/Scotty implementation

---

data/implementations.yaml

There is a lot to refactor specially when dealing with user input json (on patch and post) but it was fun to play with it :)

Adding rust/iron implementation

---

data/implementations.yaml

Learned a lot, but will keep improving this repo.
I'm using dbm as data storage due to limitations on my free Heroku account.
Will change to something better after upgrading my plan to hobby.
--
Thanks for creating this awesome showcase! :+1:

Adding python implementation using circuits.web

---

data/implementations.yaml

the specs -> http://www.todobackend.com/specs/index.html?https://todobackend-plug.herokuapp.com
This is my first app in learning elixir! Most of the implementation is taken from https://github.com/whitfieldc/maru_todo

Add elxir/plug implementation

---

data/implementations.yaml

This is an implementation in Go using only the standard libraries.

Add Golang implementation

---

data/implementations.yaml

Fixed typo in link

---

data/implementations.yaml

Added description of Vert.x with PostgreSQL implementation.

vertx + postgres

---

data/impl_tags.yaml
source/images/logos/nim.svg

SVG logo from nim-lang assets repo:
https://github.com/nim-lang/assets/tree/master/Art

Added Nim logo

---

data/implementations.yaml

It seems as though my server went down, but it has been resolved

Adds Swift / Kitura / Mongodb

---

data/implementations.yaml

Added Swift/Kitura/Cassandra implementation

---

data/implementations.yaml

Looks like some whitespace also got removed. I can add it if you'd prefer to keep the diff tight.

add vapor official todo

---

data/implementations.yaml

Hacked together a TodoBackend Falcon implementation as an exercise, so I decided to submit it here once I got all the tests passing.
Live Demo: http://todo-backend-falcon.herokuapp.com/todo
Source: https://github.com/kixpanganiban/todo-falcon
Passing Specs: http://www.todobackend.com/specs/index.html?http://todo-backend-falcon.herokuapp.com/todo

Add Falcon implementation by KixPanganiban.

---

data/implementations.yaml

http://www.todobackend.com/specs/index.html?https://todo-hapi-postgres.herokuapp.com/

Added todo-hapi-postgres

---

data/implementations.yaml

Add rails 5 with mongodb implementation

---

data/implementations.yaml

- Consists of Clojure, Compojure and H2 Local File DB

Clojure implementation using Compojure and H2 DB

---

data/implementations.yaml

Passing tests: http://www.todobackend.com/specs/index.html?https://todo-backend-aspnetcore.azurewebsites.net

Add C# ASP.NET Core implementation

---

data/implementations.yaml

new golang implementation for todo backends

Add implementation for golang with goa

---

data/implementations.yaml

Implementation with Scala and the Lift framework

---

data/implementations.yaml

all test pass : http://www.todobackend.com/specs/index.html?https://todo-backend-nutzboot.herokuapp.com/api/
logo  https://github.com/nutzam/nutz/blob/master/doc/ci/logo2.png

Add Java / NutzBoot implementation

---

data/implementations.yaml

Saw that there was no Giraffe implementation to look at for a todo backend. Made this to learn more about the framework.

F# - Giraffe

---

data/implementations.yaml

Link correction

---

data/implementations.yaml

Add Node.js/Sails implementation by Kix Panganiban. See passing specs: https://www.todobackend.com/specs/index.html?https://todo-sails.herokuapp.com/todo

Add Node.js/Sails implementation by Kix Panganiban

---

data/implementations.yaml

Kotlin with Ktor implementation

Added Ktor implementation

---

data/implementations.yaml

Fix API root for Finch implementation

Fix API root for Finch implementation

---

data/implementations.yaml

TypeScript / Node.js / Hapi.js
@mmiszy please review as the author of the forked repo

Add one more Hapi implementation

---

data/implementations.yaml

Hey everyone,
I implemented the Todo-Backend using Kotlin and [Hexagon](https://hexagonkt.com/) and would be glad to be included on the site.
Thanks in advance!

Add Kotlin / Hexagon implementation

---

data/implementations.yaml

Hi guys,
i implemented the Todo specs using C# and EventSourcing. I would be happy to see my implementation listed on your site :)
Greetings!
Sebastian

Update implementations.yaml: Added C# with DDD and EventSourcing

---

data/implementations.yaml

I was learning golang and decided to implement this using the echo golang web framework.

Add implementation using golang and echo web framework

---

data/implementations.yaml

This is a slightly different Go kit implementation using an in-memory store for demonstration purposes.

Add another Go kit example

---

data/implementations.yaml

Here is a different implementation in Scala, that also hosts Swagger UI for documentation.

Scala / endpoints4s / Swagger implementation

---

data/implementations.yaml

crystal spider-gazele clear-orm postgres

---

data/implementations.yaml

backend API with Node.js / Azure Functions / Azure SQL

added Azure SQL implementation
